// Package task contains your Go business logic.
// These functions can be called from both WASM (browser) and native Go.
package task

import (
	"fmt"
	"math/big"
)

// ProgressCallback is called with progress updates during long computations.
type ProgressCallback func(percent int, message string)

// Greet returns a greeting message. Simple example to show the pattern.
func Greet(name string) string {
	if name == "" {
		name = "World"
	}
	return fmt.Sprintf("Hello, %s! This message was generated by Go running in WebAssembly.", name)
}

// Fibonacci calculates the Nth Fibonacci number using arbitrary precision.
// Returns the result as a string since it can exceed JavaScript's Number.MAX_SAFE_INTEGER.
// Note: JavaScript loses precision at F(79). Go handles any N with math/big.
func Fibonacci(n int, onProgress ProgressCallback) (string, error) {
	if n < 0 {
		return "", fmt.Errorf("n must be non-negative, got %d", n)
	}

	if onProgress != nil {
		onProgress(0, fmt.Sprintf("Calculating F(%d)...", n))
	}

	if n == 0 {
		return "0", nil
	}
	if n == 1 {
		return "1", nil
	}

	a := big.NewInt(0)
	b := big.NewInt(1)
	temp := big.NewInt(0)

	reportInterval := n / 100
	if reportInterval < 1 {
		reportInterval = 1
	}

	for i := 2; i <= n; i++ {
		temp.Add(a, b)
		a.Set(b)
		b.Set(temp)

		if onProgress != nil && i%reportInterval == 0 {
			percent := (i * 100) / n
			digits := len(b.String())
			onProgress(percent, fmt.Sprintf("F(%d) has %d digits", i, digits))
		}
	}

	result := b.String()
	if onProgress != nil {
		digits := len(result)
		if digits > 50 {
			onProgress(100, fmt.Sprintf("F(%d) = %s...%s (%d digits)", n, result[:20], result[digits-20:], digits))
		} else {
			onProgress(100, fmt.Sprintf("F(%d) = %s", n, result))
		}
	}

	return result, nil
}

// =============================================================================
// ADD YOUR OWN FUNCTIONS BELOW
// =============================================================================
//
// Example:
//
//   func ProcessData(input []byte) ([]byte, error) {
//       // Your logic here
//       return result, nil
//   }
//
// Then export it in wasm/main.go and run `npm run wasm` to rebuild.
